// constants.js
const interests = [
    { name: "Traveling", icon: "flight" },
    { name: "Cooking", icon: "restaurant" },
    { name: "Reading", icon: "menu-book" },
    { name: "Music", icon: "music-note" },
    { name: "Dancing", icon: "music-video" },
    { name: "Movies", icon: "movie" },
    { name: "Fitness", icon: "fitness-center" },
    { name: "Sports", icon: "sports-soccer" },
    { name: "Yoga", icon: "self-improvement" },
    { name: "Photography", icon: "photo-camera" },
    { name: "Painting", icon: "brush" },
    { name: "Writing", icon: "edit" },
    { name: "Hiking", icon: "terrain" },
    { name: "Cycling", icon: "directions-bike" },
    { name: "Gaming", icon: "sports-esports" },
    { name: "Technology", icon: "devices" },
    { name: "Fashion", icon: "checkroom" },
    { name: "Shopping", icon: "shopping-cart" },
    { name: "Pets", icon: "pets" },
    { name: "Gardening", icon: "yard" },
    { name: "Meditation", icon: "self-improvement" },
    { name: "Volunteering", icon: "volunteer-activism" },
    { name: "Foodie", icon: "fastfood" },
    { name: "Art", icon: "palette" },
    { name: "Theater", icon: "theater-comedy" },
    { name: "Singing", icon: "mic" },
    { name: "Blogging", icon: "rss-feed" },
    { name: "DIY", icon: "build" },
    { name: "Crafts", icon: "content-cut" },
    { name: "Fishing", icon: "set-meal" },
    { name: "Camping", icon: "nights-stay" },
    { name: "Swimming", icon: "pool" },
    { name: "Running", icon: "directions-run" },
    { name: "Adventure Sports", icon: "sports-kabaddi" },
    { name: "Collecting", icon: "collections" },
    { name: "Investing", icon: "show-chart" },
    { name: "Travel Blogging", icon: "public" },
    { name: "Coding", icon: "code" },
    { name: "Astrology", icon: "star" },
    { name: "History", icon: "account-balance" },
    { name: "Science", icon: "science" },
    { name: "Languages", icon: "translate" },
    { name: "Board Games", icon: "extension" },
    { name: "Anime", icon: "emoji-emotions" },
    { name: "Comics", icon: "menu-book" },
    { name: "Cars", icon: "directions-car" },
    { name: "Motorcycles", icon: "two-wheeler" },
    { name: "Makeup", icon: "face-retouching-natural" },
    { name: "Interior Design", icon: "chair" },
    { name: "Stand-up Comedy", icon: "sentiment-very-satisfied" },
    { name: "Podcasts", icon: "record-voice-over" },
    { name: "Wine Tasting", icon: "wine-bar" },
    { name: "Beer Brewing", icon: "sports-bar" },
    { name: "Spirituality", icon: "self-improvement" },
    { name: "Poetry", icon: "create" },
    { name: "Astronomy", icon: "dark-mode" },
    { name: "Cooking International Food", icon: "ramen-dining" },
    { name: "Street Food", icon: "local-dining" },
    { name: "Public Speaking", icon: "campaign" },
    { name: "Social Media", icon: "share" },
    { name: "Karaoke", icon: "queue-music" },
];

module.exports = { interests };
